// utils/localization.ts — Multi-language translation dictionary (en/ru/tj)

import { Language } from '../types';

type Dictionary = Record<string, Record<Language, string>>;

const dictionary: Dictionary = {
  'Home':        { en: 'Home',        ru: 'Главная',    tj: 'Асосӣ' },
  'Insert':      { en: 'Insert',      ru: 'Вставка',    tj: 'Дарҷ' },
  'Format':      { en: 'Format',      ru: 'Формат',     tj: 'Формат' },
  'Logic':       { en: 'Logic',       ru: 'Логика',     tj: 'Мантиқ' },
  'Animations':  { en: 'Animations',  ru: 'Анимация',   tj: 'Аниматсия' },
  'View':        { en: 'View',        ru: 'Вид',        tj: 'Намуд' },
  'Plugins':     { en: 'Plugins',     ru: 'Плагины',    tj: 'Плагинҳо' },

  'File':        { en: 'File',        ru: 'Файл',       tj: 'Файл' },
  'Open':        { en: 'Open',        ru: 'Открыть',    tj: 'Кушодан' },
  'Save':        { en: 'Save',        ru: 'Сохранить',  tj: 'Захира' },
  'Preview':     { en: 'Preview',     ru: 'Просмотр',   tj: 'Пешнамоиш' },
  'Export':      { en: 'Export',      ru: 'Экспорт',    tj: 'Содирот' },

  'Clipboard':   { en: 'Clipboard',   ru: 'Буфер',      tj: 'Мубодила' },
  'Copy':        { en: 'Copy',        ru: 'Копия',      tj: 'Нусха' },
  'Paste':       { en: 'Paste',       ru: 'Вставить',   tj: 'Гузоштан' },
  'Delete':      { en: 'Delete',      ru: 'Удалить',    tj: 'Ҳазф' },

  'Basic':       { en: 'Basic',       ru: 'Базовые',    tj: 'Асосӣ' },
  'Text':        { en: 'Text',        ru: 'Текст',      tj: 'Матн' },
  'Button':      { en: 'Button',      ru: 'Кнопка',     tj: 'Тугма' },
  'Box':         { en: 'Box',         ru: 'Блок',       tj: 'Қуттӣ' },
  'Media':       { en: 'Media',       ru: 'Медиа',      tj: 'Медиа' },
  'Image':       { en: 'Image',       ru: 'Фото',       tj: 'Тасвир' },
  'Video':       { en: 'Video',       ru: 'Видео',      tj: 'Видео' },
  'Shapes':      { en: 'Shapes',      ru: 'Фигуры',     tj: 'Шаклҳо' },
  'Rect':        { en: 'Rect',        ru: 'Прямоуг.',   tj: 'Чоркунҷа' },
  'Round':       { en: 'Round',       ru: 'Скругл.',    tj: 'Гирда' },
  'Circle':      { en: 'Circle',      ru: 'Круг',       tj: 'Доира' },
  'Line':        { en: 'Line',        ru: 'Линия',      tj: 'Хат' },
  'Tri':         { en: 'Tri',         ru: 'Треуг.',     tj: 'Секунҷа' },
  'Star':        { en: 'Star',        ru: 'Звезда',     tj: 'Ситора' },
  'Arrow':       { en: 'Arrow',       ru: 'Стрелка',    tj: 'Тирча' },
  'Heart':       { en: 'Heart',       ru: 'Сердце',     tj: 'Дил' },

  'Geometry':    { en: 'Geometry',    ru: 'Геометрия',  tj: 'Геометрия' },
  'Style':       { en: 'Style',       ru: 'Стиль',      tj: 'Услуб' },
  'Fill':        { en: 'Fill',        ru: 'Заливка',    tj: 'Пуркунӣ' },
  'Border':      { en: 'Border',      ru: 'Контур',     tj: 'Сарҳад' },
  'Thickness':   { en: 'Thickness',   ru: 'Толщина',    tj: 'Ғафсӣ' },
  'Effects':     { en: 'Effects',     ru: 'Эффекты',    tj: 'Таъсирҳо' },
  'Opacity':     { en: 'Opacity',     ru: 'Прозр.',     tj: 'Шаффофият' },
  'Radius':      { en: 'Radius',      ru: 'Радиус',     tj: 'Радиус' },
  'Glass':       { en: 'Glass',       ru: 'Стекло',     tj: 'Шиша' },
  'Typography':  { en: 'Typography',  ru: 'Типография', tj: 'Типография' },
  'Text Color':  { en: 'Text Color',  ru: 'Цвет текста',tj: 'Ранги матн' },
  'Border Color':{ en: 'Border Color',ru: 'Цвет границ',tj: 'Ранги сарҳад' },

  'Events':      { en: 'Events',      ru: 'События',    tj: 'Ҳодисаҳо' },
  'Actions':     { en: 'Actions',     ru: 'Действия',   tj: 'Амалҳо' },
  'On Click':    { en: 'On Click',    ru: 'При клике',  tj: 'Зеркунӣ' },
  'On Hover':    { en: 'On Hover',    ru: 'При наведении', tj: 'Ишора' },
  'On Load':     { en: 'On Load',     ru: 'При загрузке',  tj: 'Ҳангоми боргирӣ' },
  'On Scroll':   { en: 'On Scroll',   ru: 'При скролле',   tj: 'Ҳангоми ҳаракат' },
  'No animations added': { en: 'No animations added', ru: 'Нет добавленных анимаций', tj: 'Аниматсия илова нашудааст' },
  'Bring element to life': { en: 'Bring your element to life by clicking the button above.', ru: 'Оживите элемент, нажав кнопку добавления выше.', tj: 'Элементро бо пахши тугмаи боло зинда кунед.' },
  'No Action':   { en: 'No Action',   ru: 'Нет действия',   tj: 'Бе амал' },
  'Go to Page':  { en: 'Go to Page',  ru: 'Перейти на стр.', tj: 'Гузариш ба саҳ.' },
  'Open URL':    { en: 'Open URL',    ru: 'Открыть URL',    tj: 'Кушодани URL' },
  'Show Modal':  { en: 'Show Modal',  ru: 'Показать окно',  tj: 'Нишон додани тиреза' },
  'Action':      { en: 'Action',      ru: 'Действие',       tj: 'Амал' },
  'Target Page': { en: 'Target Page', ru: 'Целевая страница', tj: 'Саҳифаи ҳадаф' },
  'URL':         { en: 'URL',         ru: 'URL',            tj: 'URL' },
  'Font Family': { en: 'Font Family', ru: 'Шрифт',          tj: 'Шрифт' },
  'Backdrop Blur':{ en: 'Backdrop Blur',ru: 'Размытие фона', tj: 'Хирагии замина' },
  'Autoplay':    { en: 'Autoplay',    ru: 'Автозапуск',     tj: 'Оғози худкор' },
  'Loop':        { en: 'Loop',        ru: 'Повтор',         tj: 'Такрор' },
  'Muted':       { en: 'Muted',       ru: 'Без звука',      tj: 'Бе садо' },
  'Add':         { en: 'Add',         ru: 'Добавить',       tj: 'Илова' },

  'Quick Animate':{ en: 'Quick Animate',ru: 'Быстрая анимация', tj: 'Аниматсияи зуд' },
  'Entrance':    { en: 'Entrance',    ru: 'Появление',      tj: 'Пайдошавӣ' },
  'Attention':   { en: 'Attention',   ru: 'Внимание',       tj: 'Диққат' },
  'Fade In':     { en: 'Fade In',     ru: 'Появление',      tj: 'Пайдошавӣ' },
  'Fade In Up':  { en: 'Fade In Up',  ru: 'Появление снизу',tj: 'Пайдошавӣ аз поён' },
  'Fade In Down':{ en: 'Fade In Down',ru: 'Появление сверху',tj:'Пайдошавӣ аз боло' },
  'Slide Up':    { en: 'Slide Up',    ru: 'Слайд вверх',    tj: 'Слайд боло' },
  'Zoom In':     { en: 'Zoom In',     ru: 'Приближение',    tj: 'Наздикшавӣ' },
  'Bounce In':   { en: 'Bounce In',   ru: 'Отскок при появлении', tj: 'Ҷаҳиш ҳангоми пайдош.' },
  'Pulse':       { en: 'Pulse',       ru: 'Пульс',          tj: 'Тапиш' },
  'Shake':       { en: 'Shake',       ru: 'Тряска',         tj: 'Ларзиш' },
  'Bounce':      { en: 'Bounce',      ru: 'Прыжок',         tj: 'Ҷаҳиш' },
  'Scale Up':    { en: 'Scale Up',    ru: 'Увеличение',     tj: 'Калоншавӣ' },
  'Continuous':  { en: 'Continuous',  ru: 'Постоянные',     tj: 'Доимӣ' },
  'Exit':        { en: 'Exit',        ru: 'Исчезновение',   tj: 'Нопадидшавӣ' },

  'Interface':   { en: 'Interface',   ru: 'Интерфейс',      tj: 'Интерфейс' },
  'Show Grid':   { en: 'Show Grid',   ru: 'Сетка',          tj: 'Панҷара' },
  'Show Layers': { en: 'Show Layers', ru: 'Слои',           tj: 'Қабатҳо' },
  'Show Properties':{ en: 'Show Properties',ru: 'Свойства', tj: 'Хусусиятҳо' },
  'Language':    { en: 'Language',    ru: 'Язык',           tj: 'Забон' },

  'Page Settings':{ en: 'Page Settings',ru: 'Настройки страницы', tj: 'Танзимоти саҳифа' },
  'Dimensions':  { en: 'Dimensions',  ru: 'Размеры',        tj: 'Андозаҳо' },
  'Background':  { en: 'Background',  ru: 'Фон',            tj: 'Замина' },
  'Props':       { en: 'Props',       ru: 'Св-ва',          tj: 'Хус.' },
  'Anim':        { en: 'Anim',        ru: 'Аним',           tj: 'Аним' },
  'Position & Size':{ en: 'Position & Size',ru: 'Позиция и Размер', tj: 'Мавқеъ ва Андоза' },
  'Appearance':  { en: 'Appearance',  ru: 'Внешний вид',    tj: 'Намуди зоҳирӣ' },
  'Content':     { en: 'Content',     ru: 'Контент',        tj: 'Муҳтаво' },
  'Size':        { en: 'Size',        ru: 'Размер',         tj: 'Андоза' },
  'Trigger':     { en: 'Trigger',     ru: 'Триггер',        tj: 'Триггер' },
  'Effect':      { en: 'Effect',      ru: 'Эффект',         tj: 'Таъсир' },
  'Duration':    { en: 'Duration',    ru: 'Длительность',   tj: 'Давомнокӣ' },
  'Delay':       { en: 'Delay',       ru: 'Задержка',       tj: 'Таваққуф' },
  'Mode':        { en: 'Mode',        ru: 'Режим',          tj: 'Реҷа' },
  'Standard':    { en: 'Standard',    ru: 'Обычный',        tj: 'Оддӣ' },
  'Fixed':       { en: 'Fixed',       ru: 'Фиксированный',  tj: 'Собит' },
  'Multiple items selected':{ en: 'Multiple items selected',ru: 'Выбрано несколько объектов', tj: 'Якчанд объект интихоб шуд' },

  'Pages':       { en: 'Pages',       ru: 'Страницы',       tj: 'Саҳифаҳо' },
  'Layers':      { en: 'Layers',      ru: 'Слои',           tj: 'Қабатҳо' },
  'Rename':      { en: 'Rename',      ru: 'Переименовать',  tj: 'Ивази ном' },
  'Duplicate':   { en: 'Duplicate',   ru: 'Дублировать',    tj: 'Нусхабардорӣ' },
  'Delete Page': { en: 'Delete Page', ru: 'Удалить страницу',tj: 'Ҳазфи саҳифа' },
  'Hyperlink':   { en: 'Hyperlink',   ru: 'Гиперссылка',    tj: 'Истинод' },
  'Cut':         { en: 'Cut',         ru: 'Вырезать',       tj: 'Буридан' },
  'Bring to Front':{ en: 'Bring to Front',ru: 'На передний план', tj: 'Ба пеш' },
  'Send to Back':{ en: 'Send to Back',ru: 'На задний план', tj: 'Ба қафо' },
};

export const t = (key: string, lang: Language): string => {
  if (!dictionary[key]) return key;
  return dictionary[key][lang] || dictionary[key]['en'];
};
